default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: longfeng_development
test:
  <<: *default
  database: longfeng_test
production:
  <<: *default
  database: longfeng_production
  username: longfeng
  password: <%= ENV['LONGFENG_DATABASE_PASSWORD'] %>
